<?php
namespace Tapsys\Checkout\Model;
use Tapsys\Checkout\Api\EndpointInterface;
use Tapsys\Checkout\Helper\Data as TapsysHelper;
use Tapsys\Checkout\Model\EnvVars;
use Magento\Framework\Session\SessionManagerInterface as CoreSession;

class Endpoint implements EndpointInterface
{
    protected $_tapsysHelper;
    protected $_coreSession;
    /**
     * @param TapsysHelper $tapsysHelper
     * @param CoreSession $coreSession
     */
    public function __construct(
        TapsysHelper $tapsysHelper,
        CoreSession $coreSession
    ) {
        $this->_tapsysHelper = $tapsysHelper;
        $this->_coreSession = $coreSession;
    }
    /**
    * Returns greeting message to user
    *
    * @api
    * @param string $currency
    * @return string Greeting message with users data.
    */
    public function data(
        $currency
    ) {
    $curr = array(
        'AFN' => '971',
        'ALL' => '8',
        'DZD' => '12',
        'USD' => '840',
        'EUR' => '978',
        'AOA' => '973',
        'XCD' => '951',
        'XCD' => '951',
        'ARS' => '32',
        'AMD' => '51',
        'AWG' => '533',
        'AUD' => '36',
        'EUR' => '978',
        'AZN' => '944',
        'BSD' => '44',
        'BHD' => '48',
        'BDT' => '50',
        'BBD' => '52',
        'BYN' => '933',
        'EUR' => '978',
        'BZD' => '84',
        'XOF' => '952',
        'BMD' => '60',
        'BTN' => '64',
        'INR' => '356',
        'BOB' => '68',
        'BOV' => '984',
        'USD' => '840',
        'BAM' => '977',
        'BWP' => '72',
        'NOK' => '578',
        'BRL' => '986',
        'USD' => '840',
        'BND' => '96',
        'BGN' => '975',
        'XOF' => '952',
        'BIF' => '108',
        'CVE' => '132',
        'KHR' => '116',
        'XAF' => '950',
        'CAD' => '124',
        'KYD' => '136',
        'XAF' => '950',
        'XAF' => '950',
        'CLF' => '990',
        'CLP' => '152',
        'CNY' => '156',
        'AUD' => '36',
        'AUD' => '36',
        'COP' => '170',
        'COU' => '970',
        'KMF' => '174',
        'CDF' => '976',
        'XAF' => '950',
        'NZD' => '554',
        'CRC' => '188',
        'HRK' => '191',
        'CUC' => '931',
        'CUP' => '192',
        'ANG' => '532',
        'EUR' => '978',
        'CZK' => '203',
        'XOF' => '952',
        'DKK' => '208',
        'DJF' => '262',
        'XCD' => '951',
        'DOP' => '214',
        'USD' => '840',
        'EGP' => '818',
        'SVC' => '222',
        'USD' => '840',
        'XAF' => '950',
        'ERN' => '232',
        'EUR' => '978',
        'ETB' => '230',
        'EUR' => '978',
        'FKP' => '238',
        'DKK' => '208',
        'FJD' => '242',
        'EUR' => '978',
        'EUR' => '978',
        'EUR' => '978',
        'XPF' => '953',
        'EUR' => '978',
        'XAF' => '950',
        'GMD' => '270',
        'GEL' => '981',
        'EUR' => '978',
        'GHS' => '936',
        'GIP' => '292',
        'EUR' => '978',
        'DKK' => '208',
        'XCD' => '951',
        'EUR' => '978',
        'USD' => '840',
        'GTQ' => '320',
        'GBP' => '826',
        'GNF' => '324',
        'XOF' => '952',
        'GYD' => '328',
        'HTG' => '332',
        'USD' => '840',
        'AUD' => '36',
        'EUR' => '978',
        'HNL' => '340',
        'HKD' => '344',
        'HUF' => '348',
        'ISK' => '352',
        'INR' => '356',
        'IDR' => '360',
        'XDR' => '960',
        'IRR' => '364',
        'IQD' => '368',
        'EUR' => '978',
        'GBP' => '826',
        'ILS' => '376',
        'EUR' => '978',
        'JMD' => '388',
        'JPY' => '392',
        'GBP' => '826',
        'JOD' => '400',
        'KZT' => '398',
        'KES' => '404',
        'AUD' => '36',
        'KPW' => '408',
        'KRW' => '410',
        'KWD' => '414',
        'KGS' => '417',
        'LAK' => '418',
        'EUR' => '978',
        'LBP' => '422',
        'LSL' => '426',
        'ZAR' => '710',
        'LRD' => '430',
        'LYD' => '434',
        'CHF' => '756',
        'EUR' => '978',
        'EUR' => '978',
        'MOP' => '446',
        'MGA' => '969',
        'MWK' => '454',
        'MYR' => '458',
        'MVR' => '462',
        'XOF' => '952',
        'EUR' => '978',
        'USD' => '840',
        'EUR' => '978',
        'MRU' => '929',
        'MUR' => '480',
        'EUR' => '978',
        'XUA' => '965',
        'MXN' => '484',
        'MXV' => '979',
        'USD' => '840',
        'MDL' => '498',
        'EUR' => '978',
        'MNT' => '496',
        'EUR' => '978',
        'XCD' => '951',
        'MAD' => '504',
        'MZN' => '943',
        'MMK' => '104',
        'NAD' => '516',
        'ZAR' => '710',
        'AUD' => '36',
        'NPR' => '524',
        'EUR' => '978',
        'XPF' => '953',
        'NZD' => '554',
        'NIO' => '558',
        'XOF' => '952',
        'NGN' => '566',
        'NZD' => '554',
        'AUD' => '36',
        'USD' => '840',
        'NOK' => '578',
        'OMR' => '512',
        'PKR' => '586',
        'USD' => '840',
        'PAB' => '590',
        'USD' => '840',
        'PGK' => '598',
        'PYG' => '600',
        'PEN' => '604',
        'PHP' => '608',
        'NZD' => '554',
        'PLN' => '985',
        'EUR' => '978',
        'USD' => '840',
        'QAR' => '634',
        'MKD' => '807',
        'RON' => '946',
        'RUB' => '643',
        'RWF' => '646',
        'EUR' => '978',
        'EUR' => '978',
        'SHP' => '654',
        'XCD' => '951',
        'XCD' => '951',
        'EUR' => '978',
        'EUR' => '978',
        'XCD' => '951',
        'WST' => '882',
        'EUR' => '978',
        'STN' => '930',
        'SAR' => '682',
        'XOF' => '952',
        'RSD' => '941',
        'SCR' => '690',
        'SLL' => '694',
        'SGD' => '702',
        'ANG' => '532',
        'XSU' => '994',
        'EUR' => '978',
        'EUR' => '978',
        'SBD' => '90',
        'SOS' => '706',
        'ZAR' => '710',
        'SSP' => '728',
        'EUR' => '978',
        'LKR' => '144',
        'SDG' => '938',
        'SRD' => '968',
        'NOK' => '578',
        'SZL' => '748',
        'SEK' => '752',
        'CHE' => '947',
        'CHF' => '756',
        'CHW' => '948',
        'SYP' => '760',
        'TWD' => '901',
        'TJS' => '972',
        'TZS' => '834',
        'THB' => '764',
        'USD' => '840',
        'XOF' => '952',
        'NZD' => '554',
        'TOP' => '776',
        'TTD' => '780',
        'TND' => '788',
        'TRY' => '949',
        'TMT' => '934',
        'USD' => '840',
        'AUD' => '36',
        'UGX' => '800',
        'UAH' => '980',
        'AED' => '784',
        'GBP' => '826',
        'USD' => '840',
        'USD' => '840',
        'USN' => '997',
        'UYI' => '940',
        'UYU' => '858',
        'UZS' => '860',
        'VUV' => '548',
        'VEF' => '937',
        'VND' => '704',
        'USD' => '840',
        'USD' => '840',
        'XPF' => '953',
        'MAD' => '504',
        'YER' => '886',
        'ZMW' => '967',
        'ZWL' => '932',
        'EUR' => '978'
        );
    $env = (bool)$this->_tapsysHelper->getStoreConfigValue('sandbox');
    $tokenApiBaseUrl = $env ? EnvVars::SANDBOX_API_URL : EnvVars::PRODUCTION_API_URL;
    $url = $tokenApiBaseUrl . EnvVars::INIT_TRANSACTION_ENDPOINT;
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $cart = $objectManager->get('\Magento\Checkout\Model\Cart');
    $grandTotal = $cart->getQuote()->getGrandTotal();
    $billing_address = $cart->getQuote()->getBillingAddress();
    $billing_address = $billing_address->getData();
    $shipping_address = $cart->getQuote()->getShippingAddress();
    $shipping_address = $shipping_address->getData();
    $customer_email = $cart->getQuote()->getBillingAddress()->getEmail();
    if(isset($shipping_address['street']) && strlen($shipping_address['street']) > 0){$address = $shipping_address;}
    if(isset($billing_address['street']) && strlen($billing_address['street']) > 0){$address = $billing_address;}
    $fields = array(
        'url' => $url,
        'firstName' => $address['firstname'],
        'lastName' => $address['lastname'],
        'billingEmail' => $customer_email,
        'environment' => $env ? 'sandbox' : 'production',
        'clientId' => $env ? $this->_tapsysHelper->getStoreConfigValue('sandbox_key') : $this->_tapsysHelper->getStoreConfigValue('production_key'),
        'clientWordPressKey' => $this->_tapsysHelper->getSharedSecret(),
        'merchantId' => $this->_tapsysHelper->getStoreConfigValue('merchant_id'),
        'billingAddress' => $address['street'] . " " . $address['city'] . " " . $address['postcode'] . " " . $address['country_id'],
        'billingPhone' => $address['telephone'],
        'amount' => $grandTotal,
        'currency' => $curr[$currency]
    );
    $fields = json_encode($fields);
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $result = curl_exec($ch);
    $token = json_decode($result);
    $this->_coreSession->start();
    $this->_coreSession->setMyVariable($token->data->token."-_-".$grandTotal);
    return "OK";
  }
}
